coin_symbols = ['STPT', 'MXN', 'UGX', 'RENBTC', 'GLM', 'NEAR', 'AUDIO', 'HNT', 'ADADOWN', 'CDT', 'SPARTA', 'SUSD',
                'AION',
                'NPXS', 'DGB', 'ZRX', 'BCD', 'EASY', 'WING', 'AE', 'WNXM', 'BCH', 'JST', 'ADAUP', 'HOT', 'AR', 'IRIS',
                'RAMP', 'BCX', 'SEK', 'TRIG', 'RCN', 'COVER', 'FLM', 'VITE', 'GNT', 'BKRW', 'CFX', 'XPR', 'SFP', 'DIA',
                'RDN', 'ARDR', 'CLOAK', 'LOOMOLD', 'NEBL', 'SLPOLD', 'BEL', 'JUV', 'ACM', 'GRTDOWN', 'VTHO', 'SALT',
                'STORM',
                'REN', 'REP', 'ADA', 'ELF', 'REQ', 'STORJ', 'CHF', 'BZRX', 'ADD', 'SGT', 'DF', 'EOSDOWN', 'PAXG',
                'YOYO',
                'PAX', 'CHR', 'VND', 'BCHDOWN', 'WAVES', 'CHZ', 'ADX', 'XRP', 'WPR', 'AED', 'SAND', 'DKK', 'OCEAN',
                'FOR',
                'UMA', 'DREPOLD', 'SCRT', 'TUSD', 'EZ', 'TKO', 'WABI', 'IDRT', 'ENG', 'ENJ', 'UNIDOWN', 'YFII', 'KZT',
                'OAX',
                'GRT', 'GRS', 'UND', 'HARD', 'TFUEL', 'LEND', 'DLT', 'TROY', 'XLMUP', 'UNI', 'BTCDOWN', 'TLM', 'HUF',
                'SBTC',
                'CKB', 'WRX', 'XTZ', 'LUNA', 'ETHDOWN', 'BCHA', 'EON', 'EOP', 'EOS', 'GO', 'NCASH', 'RIF', 'EOSBULL',
                'NSBT',
                'SKL', 'GTC', 'PEN', 'BLINK', 'SXPDOWN', 'HC', 'SKY', 'BURGER', 'NAS', 'NAV', 'GTO', 'WTC', 'XVG',
                'EPS',
                'TNB', 'DNT', 'BULL', 'CLV', 'FLOW', 'XTZDOWN', 'XVS', 'STEEM', 'BVND', 'SLP', 'VRT', 'NBS', 'DON',
                'DOT',
                'IQ', 'CMT', 'GRTUP', '1INCH', 'KNCL', 'XRPBULL', 'MITH', 'ERD', 'DEGO', 'CND', 'GYEN', 'UNFI', 'FTM',
                'POWR', 'ERN', 'GVT', 'WINGS', 'FTT', 'PHA', 'RLC', 'PHB', 'TRXDOWN', 'ATOM', 'XRPUP', 'QUICK', 'BLZ',
                'SNM',
                'MBL', 'BNBUP', 'MTLX', 'SNT', 'PHP', 'SNX', 'LTCDOWN', 'FUN', 'SNMOLD', 'COS', 'USD', 'QKC', 'SUSHIUP',
                'ROSE', 'XYM', 'SOL', 'TRXUP', 'ETC', 'ETF', 'BNB', 'CELR', 'OGN', 'ETH', 'NEO', 'TOMO', 'CELO', 'KLAY',
                'AUCTION', 'BADGER', 'GXS', 'TRB', 'BNT', 'QLC', 'LBA', 'MDA', 'UTK', 'EOSBEAR', 'HEGIC', 'AMB', 'TRU',
                'WBNB', 'FUEL', 'DREP', 'TRY', 'TRX', 'MDT', 'NFT', 'MDX', 'XRPDOWN', 'AERGO', 'EUR', 'BOT', 'NULS',
                'AUTO',
                'NGN', 'EGLD', 'ANTOLD', 'PUNDIX', 'FXS', 'HNST', 'EVX', 'CRV', 'BAKE', 'ANT', 'NU', 'LINKUP', 'SRM',
                'TORN',
                'PLN', 'QNT', 'ETHBEAR', 'ALICE', 'OG', 'MFT', 'OM', 'BETH', 'BQX', 'WETH', 'BRD', 'BUSD', 'CTK',
                'ARPA',
                'DOTDOWN', 'BRL', 'CTR', 'MATIC', 'IOTX', 'SHIB', 'TVK', 'FRONT', 'ZAR', 'DOCK', 'STX', 'PNT', 'DENT',
                'QI',
                'BNBBEAR', 'SUB', 'POA', 'IOST', 'CAKE', 'ETHUP', 'POE', 'OMG', 'BAND', 'SUN', 'SUNOLD', 'BTC', 'TWT',
                'NKN',
                'RSR', 'IOTA', 'CVC', 'REEF', 'BTG', 'MIR', 'KES', 'ARK', 'CVP', 'ARN', 'KEY', 'BTS', 'SPARTAOLD',
                'ARS',
                'BTT', 'ONE', 'LINKDOWN', 'ONG', 'ANKR', 'SUSHI', 'ALGO', 'SC', 'WBTC', 'ONT', 'PPT', 'ONX', 'RUB',
                'PIVX',
                'ASR', 'FIRO', 'AXSOLD', 'AST', 'MANA', 'DOTUP', 'ATA', 'MEETONE', 'QSP', 'ATD', 'NMR', 'MKR', 'DODO',
                'LIT',
                'ICP', 'ZEC', 'ATM', 'APPC', 'JEX', 'ICX', 'LOOM', 'ZEN', 'KP3R', 'DOGE', 'DUSK', 'ALPHA', 'BOLT',
                'SXP',
                'HBAR', 'RVN', 'MLN', 'AUD', 'NANO', 'IDR', 'CTSI', 'KAVA', 'C98', 'PSG', 'HCC', 'VIDT', 'NOK', 'AVA',
                'SYS',
                'COCOS', 'STRAX', 'EOSUP', 'CZK', 'GAS', 'COVEROLD', 'THETA', 'AAVEDOWN', 'BCHUP', 'WAN', 'ORN', 'PERL',
                'XLMDOWN', 'MASK', 'AAVE', 'XRPBEAR', 'GBP', 'PERP', '1INCHUP', 'SXPUP', 'YFIDOWN', 'BOND', 'YFI',
                'PERLOLD',
                'MOD', 'OST', 'XEC', 'AXS', 'ZIL', 'VAI', 'XEM', 'CTXC', 'KEYFI', 'XTZUP', 'BIDR', 'BCHSV', 'AAVEUP',
                'SUSHIDOWN', 'COMP', 'ETHBNT', 'OMOLD', 'RUNE', 'FORTH', 'KMD', 'GHST', 'IDEX', 'BNBDOWN', 'DEXE',
                'AVAX',
                'UAH', 'KNC', 'PROS', 'PROM', 'BTCUP', 'CHAT', 'BGBP', 'LPT', 'HIVE', 'BIFI', 'SNGLS', 'DAI', 'YFIUP',
                'FET',
                'ETHBULL', 'LRC', 'REPV1', 'ADXOLD', 'MTH', 'MTL', 'VET', 'USDT', 'USDS', 'OXT', 'DASH', 'NVT', 'SWRV',
                'EDO', 'GHS', 'BTCST', 'HKD', 'LSK', 'KEEP', 'CAD', 'BEAR', 'BEAM', 'CAN', 'DCR', 'CREAM', 'DATA',
                'ENTRP',
                'FILUP', 'UNIUP', 'LTC', 'USDC', 'WIN', 'BNBBULL', 'LTCUP', 'INJ', 'TCT', 'LTO', 'NXS', 'AGIX', 'INR',
                'CBK',
                'CBM', 'INS', 'POND', 'JPY', 'LINA', 'XLM', 'LINK', 'QTUM', 'FILDOWN', 'SUPER', 'UFT', 'POLS', 'KSM',
                'LUN',
                'FIL', 'POLY', 'STMX', 'BAL', 'FIO', 'VIB', 'VIA', 'FIS', 'BAR', 'BAT', 'VRAB', 'AKRO', 'NZD', 'XMR',
                '1INCHDOWN', 'COTI']
